version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket ServerlessOps-deploymentbucket-igngar 
                                   --output-template-file SAM-template.yaml
artifacts:
  type: zip
  files:
    - SAM-template.yaml