AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with API defined in an external Swagger file along with Lambda integrations and CORS configurations


Globals:
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST'"
      AllowHeaders: "'Content-Type, Authorization, X-Amz-Date, X-Api-Key, X-Amz-Security-Token'"
      AllowOrigin: "'*'"
      MaxAge: "'600'"

Resources:
  LambdaFunction:
   Type: AWS::Serverless::Function
   Properties:
      CodeUri: functions/getinfo
      Description: "Backend Lambda for Serverless Ops Workshop"
      Handler: index.handler
      Timeout: 60
      Policies: 
        - AmazonRekognitionFullAccess
        - AmazonS3ReadOnlyAccess
      Runtime: nodejs4.3
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /getinfo
            Method: POST
      AutoPublishAlias: live

Outputs:
  ApiURL:
      Description: "API endpoint URL for Prod environment"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"