AWSTemplateFormatVersion: 2010-09-09
Description: "Template with the all the steps previous to the workshop."
Resources:
  ServerlessOpsFrontend:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
  
  ServerlessOpsDeployments:
    Type: 'AWS::S3::Bucket'

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ServerlessOpsFrontend
                - /*
      Bucket: !Ref ServerlessOpsFrontend

  ServerlessOpsCodeBuild:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codebuild.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "root"
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Resource: "*"
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            - Effect: Allow
              Resource: "*"
              Action: "s3:*"
            - Effect: Allow
              Action:
              - ssm:GetParameters
              Resource: "*"
      RoleName: "ServerlessOps-codebuildrole"

  
  ServerlessOpsCloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "root"
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Resource: "*"
              Action: 
              - "apigateway:*"
              - "iam:*"
              - "lambda:*"
              - "codedeploy:*"
              - "cloudformation:*"
              - "s3:*"
      RoleName: "ServerlessOps-cloudformationrole"